ovirt:
  username: vale@internal
  ca_file: /etc/pki/ovirt-engine/ca.pem
  password: <insert-pass-here>
  data_center: Default
  cluster: Default
  host: ovirt.righini.local
  engine: ovengine.righini.local
  storage:
     interface: virtio
     storage_domain: 2t_2
  network:
    external:
       interface: virtio
       profile: vlan19
       network: vlan19
    internal:
       interface: virtio
       profile: vlan_1
       network: vlan_1
       host_interface: ens786f1 #Insert oVirt host interface name
       vlan_tag: 1