ovirt:
  username: vale@internal
  ca_file: /etc/pki/ovirt-engine/ca.pem
  password: valevale
  data_center: Default
  cluster: Default
  host: ovirt01
  engine: ovengine01.seeweb.local
  storage:
     interface: virtio
     storage_domain: 2t_2
  network:
    external:
       interface: virtio
       profile: vlan19
       network: vlan19
    internal:
       interface: virtio
       profile: vlan_2
       network: vlan_2
       host_interface: eno2 #Insert oVirt host interface name
       vlan_tag: 2