ovirt:
  username: admin@internal
  ca_file: /etc/pki/ovirt-engine/ca.pem
  password: toor
  data_center: Default
  cluster: Default
  host: host.mylab.com
  engine: manager.mylab.com
  storage:
     interface: virtio
     storage_domain: hosted_storage
  network:
    external:
       interface: virtio
       profile: ovirtmgmt
       network: ovirtmgmt
    internal:
       interface: virtio
       profile: ocp
       network: ocp
       host_interface: em2


networking:
  internal_network: 172.22.0.0
  internal_network_ip: 172.22.0.1
  internal_network_netmask: 255.255.255.0
  external_dns: 192.168.1.77
  domain_name: mylab.com

dhcp:
  timezone: "Europe/Rome"
  start: 172.22.0.201
  end: 172.22.0.250
  ntp: 204.11.201.10

bastion:
  name: bastion
  public_ip: 192.168.1.101
  public_netmask: 255.255.255.0
  public_gateway: 192.168.1.1

firewall_services:
  - http
  - dns
  - dhcp

firewall_public_ha_proxy_port:
  - 80/tcp
  - 443/tcp
  - 6443/tcp
  

ocp:
  reserved_ip:
    api: 172.22.0.2
    apps: 172.22.0.3
    internal_dns: 172.22.0.4 # Used by installer
  cluster_name: ocp
  domain: mylab.com

