networking:
  internal_network: 172.27.4.0
  internal_network_ip: 172.27.4.1
  internal_network_netmask: 255.255.255.0
  external_dns: 172.19.0.200
  domain_name: lab.seeweb

dhcp:
  timezone: "Europe/Rome"
  start: 172.27.4.201
  end: 172.27.4.250
  ntp: 204.11.201.10

bastion:
  name: bastionhub
  public_ip: 172.19.0.100
  public_netmask: 255.255.255.0
  public_gateway: 10.40.0.254


firewall_services:
  - http
  - dns
  - dhcp

firewall_public_ha_proxy_port:
  - 80/tcp
  - 443/tcp
  - 6443/tcp
  

ocp:
  user: vale
  pass: 
  reserved_ip:
    api: 172.27.4.2
    apps: 172.27.4.3
  cluster_name: ocphub
  pull_secret: ''
  

